#!/bin/bash

function main() {
        set -euo pipefail
        case "${1}" in
                remove)
                systemctl stop wildfly || true
                systemctl disable wildfly || true
                systemctl daemon-reload
                ;;
                upgrade)
                . "/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/helper.sh"
                remove_entry_from_service "wildfly.service" "Requires" "postgresql.service"
                remove_entry_from_service "wildfly.service" "After" "postgresql.service"
                ;;
        esac
}
