#!/bin/bash
systemctl stop wildfly || true
systemctl disable wildfly || true

# remove postgresql dependency on wildfly.service
. "/usr/share/$DPKG_MAINTSCRIPT_PACKAGE/helper.sh"
remove_entry_from_service "postgresql.service" "Requires" "wildfly.service"
remove_entry_from_service "postgresql.service" "Before" "wildfly.service"

# remove update hold for postgresql-12
sed '/Package: postgresql-12/{N;N;d;}' /etc/apt/preferences.d/official-package-repositories.pref

systemctl daemon-reload
